//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HocSinhMVC.Helper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HocSinhMVC.Helper.res", typeof(res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sach trong.
        /// </summary>
        internal static string ErrDanhSachTrong {
            get {
                return ResourceManager.GetString("ErrDanhSachTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can nhap so nguyen!.
        /// </summary>
        internal static string ErrIDHS {
            get {
                return ResourceManager.GetString("ErrIDHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khong tim thay ma.
        /// </summary>
        internal static string ErrKhongThayMa {
            get {
                return ResourceManager.GetString("ErrKhongThayMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can nhap ngay sinh tu 01/01/2005 - 31/12/2016!.
        /// </summary>
        internal static string ErrNgSinh {
            get {
                return ResourceManager.GetString("ErrNgSinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can nhap ten hoc sinh tu 6 - 20 ky tu!.
        /// </summary>
        internal static string ErrTen {
            get {
                return ResourceManager.GetString("ErrTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuc hien thanh cong.
        /// </summary>
        internal static string ErrThanhCong {
            get {
                return ResourceManager.GetString("ErrThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma da bi trung.
        /// </summary>
        internal static string ErrTrungMa {
            get {
                return ResourceManager.GetString("ErrTrungMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ma hoc sinh:.
        /// </summary>
        internal static string InpIDHS {
            get {
                return ResourceManager.GetString("InpIDHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ngay sinh:.
        /// </summary>
        internal static string InpNgSinh {
            get {
                return ResourceManager.GetString("InpNgSinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ten hoc sinh:.
        /// </summary>
        internal static string InpTen {
            get {
                return ResourceManager.GetString("InpTen", resourceCulture);
            }
        }
    }
}
